### ISSUE TITLE
Running the Demo, I get 502 Bad Gateway

### ISSUE THREAD

**Issue by c0d3x** [kairosinc/api-examples#8] opened 2017-05-13 01:17 UTC
I am running Linux Mint 18.1(ubuntu xenial based)

I cloned the repo to kairos-api folder.
- Added the API keys
- Changed the docker name referance in Makefile
- I also had an error with EXIF, which I solved by commenting out that line as it is provided by default.

When image is up and running and I try to access the docker image on:
http://localhost:8080/

I am getting the: 502 Bad Gateway nginx/1.10.1
So I get to the container nginx, but there is no data there.

Here is the terminal log:

```
kairos-api $ sudo make build && sudo make run
docker build  -t demo .
Sending build context to Docker daemon 32.17 MB
Step 1/6 : FROM kairos/nginx-php-alpine:latest
latest: Pulling from kairos/nginx-php-alpine
e110a4a17941: Pull complete 
3f504fc01783: Pull complete 
9067587fa9c1: Pull complete 
db82289b6532: Pull complete 
bf390e1a51c6: Pull complete 
d048952484cb: Pull complete 
Digest: sha256:6886cc01a178e25e01d864dbef0b99bd5bb68b30d22f5a2c6b66f074ef067fc7
Status: Downloaded newer image for kairos/nginx-php-alpine:latest
 ---> 851736af71bc
Step 2/6 : MAINTAINER Cole Calistra <cole@kairos.com>
 ---> Running in 40c1d6192a10
 ---> 24e4befa3477
Removing intermediate container 40c1d6192a10
Step 3/6 : COPY . /tmp
 ---> 054a1adaa00a
Removing intermediate container 87c0ce702695
Step 4/6 : RUN apk update && apk add php5-gd php5-imagick ghostscript ghostscript-fonts php5-exif
 ---> Running in 0a3f25fdf6db
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
v3.4.6-116-g2862a47 [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.6-83-g67e50bc [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
OK: 6005 distinct packages available
(1/26) Installing dbus-libs (1.10.8-r1)
(2/26) Installing libintl (0.19.7-r3)
(3/26) Installing avahi-libs (0.6.32-r0)
(4/26) Installing libgcc (5.3.0-r0)
(5/26) Installing gmp (6.1.0-r0)
(6/26) Installing nettle (3.2-r0)
(7/26) Installing libtasn1 (4.8-r0)
(8/26) Installing p11-kit (0.23.2-r0)
(9/26) Installing gnutls (3.4.15-r0)
(10/26) Installing libstdc++ (5.3.0-r0)
(11/26) Installing cups-libs (2.1.3-r1)
(12/26) Installing libpng (1.6.21-r0)
(13/26) Installing freetype (2.6.3-r0)
(14/26) Installing fontconfig (2.12.1-r0)
(15/26) Installing jbig2dec (0.12-r0)
(16/26) Installing libjpeg-turbo (1.4.2-r0)
(17/26) Installing lcms2 (2.8-r0)
(18/26) Installing tiff (4.0.7-r2)
(19/26) Installing ghostscript (9.19-r2)
(20/26) Installing ghostscript-fonts (8.11-r1)
(21/26) Installing php5-exif (5.6.30-r0)
(22/26) Installing php5-gd (5.6.30-r0)
(23/26) Installing libgomp (5.3.0-r0)
(24/26) Installing libwebp (0.5.0-r0)
(25/26) Installing imagemagick (6.9.5.9-r1)
(26/26) Installing php5-imagick (3.4.2-r1)
Executing busybox-1.24.2-r9.trigger
Executing fontconfig-2.12.1-r0.trigger
OK: 176 MiB in 81 packages
 ---> 53afbae18d3a
Removing intermediate container 0a3f25fdf6db
Step 5/6 : RUN cp -Rf /tmp/* /var/www/app/                       &&     cp /tmp/conf/default.conf /etc/nginx/conf.d/      &&     rm -Rf /var/www/app/conf /var/www/app/Dockerfile  &&     cp /tmp/scripts/nginx_env.sh  /usr/local/bin/     &&     chmod +x /usr/local/bin/nginx_env.sh              &&     rm -Rf /tmp/*                                     &&     touch /var/log/access.log /var/log/error.log      &&     touch /var/run/php-fpm.sock                       &&     touch /var/log/php-fpm.log /var/log/demo.log      &&     ln -sf /dev/stderr /var/log/php-fpm.log           &&     ln -sf /dev/stdout /var/log/demo.log              &&     ln -sf /dev/stdout /var/log/nginx/access.log      &&     ln -sf /dev/stderr /var/log/nginx/error.log       &&     sed -i -e "s/memory_limit = 128M/memory_limit = 512M/g" /etc/php5/php.ini &&     chown -R nginx:nginx /var/log/* /etc/nginx/*      &&     chown -R nginx:nginx /var/www/* /etc/php5/*       &&     cd /var/www/app/demo && composer update
 ---> Running in b7cfc03e8694
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
 ---> dfacfbfbfe8e
Removing intermediate container b7cfc03e8694
Step 6/6 : WORKDIR /var/log
 ---> 32eec92c7120
Removing intermediate container 8bc42c050b39
Successfully built 32eec92c7120
docker-compose up -d
Creating kairosapi_demo_1 ... 
Creating kairosapi_demo_1 ... done
docker exec kairosapi_demo_1 composer update -d /var/www/app/demo
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by c0d3x** [comment] 2017-05-13 01:26
Here is the docker-compose logs, hope that solves the issue:

```
docker-compose logs -f
Attaching to kairosapi_demo_1
demo_1  | fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
demo_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
demo_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
demo_1  | ERROR: unsatisfiable constraints:
demo_1  |   php5-xdebug (missing):
demo_1  |     required by: world[php5-xdebug]
demo_1  | 2017-05-13 01:05:10,008 CRIT Set uid to user 0
demo_1  | 2017-05-13 01:05:10,017 INFO RPC interface 'supervisor' initialized
demo_1  | 2017-05-13 01:05:10,017 CRIT Server 'unix_http_server' running without any HTTP authentication checking
demo_1  | 2017-05-13 01:05:10,017 INFO supervisord started with pid 51
demo_1  | 2017-05-13 01:05:11,019 INFO spawned: 'php-fpm' with pid 54
demo_1  | 2017-05-13 01:05:11,021 INFO spawned: 'nginx' with pid 55
demo_1  | Failed loading /usr/lib/php5/modules/:  Error loading shared library /usr/lib/php5/modules/: Is a directory
demo_1  | [13-May-2017 01:05:11] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [13-May-2017 01:05:11] ERROR: [/etc/php5/php-fpm.conf:543] empty value
demo_1  | [13-May-2017 01:05:11] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [13-May-2017 01:05:11] ERROR: FPM initialization failed
demo_1  | 2017-05-13 01:05:11,065 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-13 01:05:12,067 INFO spawned: 'php-fpm' with pid 64
demo_1  | 2017-05-13 01:05:12,068 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
demo_1  | Failed loading /usr/lib/php5/modules/:  Error loading shared library /usr/lib/php5/modules/: Is a directory
demo_1  | [13-May-2017 01:05:12] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [13-May-2017 01:05:12] ERROR: [/etc/php5/php-fpm.conf:543] empty value
demo_1  | [13-May-2017 01:05:12] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [13-May-2017 01:05:12] ERROR: FPM initialization failed
demo_1  | 2017-05-13 01:05:12,108 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-13 01:05:14,111 INFO spawned: 'php-fpm' with pid 65
demo_1  | Failed loading /usr/lib/php5/modules/:  Error loading shared library /usr/lib/php5/modules/: Is a directory
demo_1  | [13-May-2017 01:05:14] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [13-May-2017 01:05:14] ERROR: [/etc/php5/php-fpm.conf:543] empty value
demo_1  | [13-May-2017 01:05:14] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [13-May-2017 01:05:14] ERROR: FPM initialization failed
demo_1  | 2017-05-13 01:05:14,150 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017/05/13 01:05:16 [crit] 56#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.18.0.1 - - [13/May/2017:01:05:16 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
demo_1  | 2017-05-13 01:05:17,228 INFO spawned: 'php-fpm' with pid 66
demo_1  | Failed loading /usr/lib/php5/modules/:  Error loading shared library /usr/lib/php5/modules/: Is a directory
demo_1  | [13-May-2017 01:05:17] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [13-May-2017 01:05:17] ERROR: [/etc/php5/php-fpm.conf:543] empty value
demo_1  | [13-May-2017 01:05:17] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [13-May-2017 01:05:17] ERROR: FPM initialization failed
demo_1  | 2017-05-13 01:05:17,259 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017/05/13 01:05:17 [crit] 56#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 2017-05-13 01:05:17,329 INFO gave up: php-fpm entered FATAL state, too many start retries too quickly
demo_1  | 172.18.0.1 - - [13/May/2017:01:05:17 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
demo_1  | 2017/05/13 01:05:18 [crit] 56#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.18.0.1 - - [13/May/2017:01:05:18 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
demo_1  | 2017/05/13 01:05:18 [crit] 56#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.18.0.1 - - [13/May/2017:01:05:18 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
demo_1  | 2017/05/13 01:05:18 [crit] 56#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.18.0.1 - - [13/May/2017:01:05:18 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"

```

**Comment by coleca** [comment] 2017-05-13 03:17
Hi, 

I just pushed a fix up (https://github.com/kairosinc/api-examples/commit/86a3f5df11812a0f99c75630b373597c43b0bbf4) to correct the issues and cleanup the error messages in the logs.  

The issue is that the env vars in docker-compose.yml all needed default values for PHP5-FPM to start properly.

Thanks for catching this!

**Closed as completed by coleca** 2017-05-13 03:17 UTC
